### ISSUE TITLE
F1855 不是V2 支持Bonding嘛？

### ISSUE THREAD

**Issue by jackiehj** [qweraqq/qweraqq.github.io#1]
我是上海电信，中兴F1855不是V2版。改了桥接，接N5105 2.5G端口的软路由，ikuai拨号，ikuai系统下有个Wan链路聚合。我现在用2根线从光猫接软路由，测速下来有时候可以1200M，有时候只有945M，但大多时间都在945M！是因为光猫不支持Bonding嘛？还是其他原因？换个带Q的光猫会有改善吗？

**Comment by jackiehj** [comment]
你的F1855 V2 能支持Bonding嘛？那你现在测速能稳定在1200M左右吗？

**Comment by qweraqq** [comment]
测速服务器端的问题
